DISEASE_KB = {

     "bacterial_leaf_blight": {
        "name": "Bacterial Leaf Blight",
        "treatment": "Streptocycline @ 0.01% + Copper oxychloride @ 0.25% (spray)",
        "prevention": "Use disease-free seeds, avoid overhead irrigation, maintain proper plant spacing",
        "application_method": "Spray during early morning or late evening, cover all leaf surfaces thoroughly",
        "secondary_treatment": "Copper hydroxide or Copper sulfate as alternative copper formulations",
        "recommended_products": ["Streptocycline 90% SP", "Copper oxychloride 50% WP", "Blue copper"],
        "timing": "Apply at first symptom appearance, repeat every 7-10 days if needed",
        "frequency": "2-3 applications during critical growth stages",
        "safety_notes": "Wear protective clothing, avoid spray drift to water bodies",
        "weather_considerations": "Avoid application during rain or when rain is expected within 4 hours",
        "crop_stage_compatibility": "Safe for all growth stages, most effective during vegetative phase",
        "soil_compatibility": "Compatible with all soil types, avoid waterlogged conditions",
        "estimated_cost": "₹800-1200 per hectare per application",
        "effectiveness_duration": "7-10 days protection",
        "reapplication_needed": "Monitor weekly and reapply if new symptoms appear"
    },
    
    "bacterial_leaf_streak": {
        "name": "Bacterial Leaf Streak",
        "treatment": "Copper oxychloride @ 0.25% or Streptocycline (low concentration, preventive)",
        "prevention": "Remove infected plant debris, practice crop rotation, use resistant varieties",
        "application_method": "Preventive spray application with good coverage of leaf surfaces",
        "secondary_treatment": "Kasugamycin or Validamycin for bacterial control",
        "recommended_products": ["Copper oxychloride 50% WP", "Streptomycin sulfate", "Kasumin 2% SL"],
        "timing": "Preventive application before disease onset or at very early symptoms",
        "frequency": "1-2 preventive applications during susceptible periods",
        "safety_notes": "Use proper spray equipment calibration, maintain buffer zones",
        "weather_considerations": "Apply in calm weather, avoid high temperature periods",
        "crop_stage_compatibility": "Preventive treatment most effective during early growth",
        "soil_compatibility": "Good drainage helps prevent disease development",
        "estimated_cost": "₹600-900 per hectare per application",
        "effectiveness_duration": "10-14 days preventive protection",
        "reapplication_needed": "Reapply after heavy rains or if conditions favor disease"
    },

    "bacterial_panicle_blight": {
        "name": "Bacterial Panicle Blight",
        "treatment": "Hot water seed treatment (52°C for 30 min) and preventive Streptocycline spray",
        "prevention": "Use certified disease-free seeds, treat seeds before planting, avoid water stress",
        "application_method": "Seed treatment followed by foliar spray application during critical stages",
        "secondary_treatment": "Copper-based bactericides during flowering stage",
        "recommended_products": ["Streptocycline 90% SP", "Copper hydroxide 77% WP", "Seed treatment fungicides"],
        "timing": "Seed treatment before planting, foliar spray during panicle development",
        "frequency": "Seed treatment once, foliar spray 1-2 times during reproductive phase",
        "safety_notes": "Maintain precise temperature during seed treatment, use protective equipment",
        "weather_considerations": "Avoid foliar application during flowering to prevent phytotoxicity",
        "crop_stage_compatibility": "Critical treatment during panicle initiation and development",
        "soil_compatibility": "Well-drained soils reduce disease incidence",
        "estimated_cost": "₹1000-1500 per hectare including seed treatment",
        "effectiveness_duration": "Season-long protection from seed treatment",
        "reapplication_needed": "Foliar spray may be repeated if disease pressure is high"
    },
    
    "blast": {
        "name": "Rice Blast",
        "treatment": "Tricyclazole 75% WP @ 0.6 g per liter of water or Isoprothiolane @ 1.5 ml per liter",
        "prevention": "Use resistant varieties, balanced nitrogen fertilization, proper water management",
        "application_method": "Thorough foliar spray ensuring complete leaf coverage, especially lower leaves",
        "secondary_treatment": "Propiconazole or Tebuconazole as systemic alternatives",
        "recommended_products": ["Tricyclazole 75% WP (Beam)", "Isoprothiolane 40% EC", "Propiconazole 25% EC"],
        "timing": "Apply at first symptom appearance or during high-risk periods (humid weather)",
        "frequency": "2-3 applications at 10-14 day intervals during susceptible growth stages",
        "safety_notes": "Rotate fungicides to prevent resistance development, follow label rates strictly",
        "weather_considerations": "Most effective when applied before infection occurs, avoid during rain",
        "crop_stage_compatibility": "Critical periods: seedling, tillering, and heading stages",
        "soil_compatibility": "Avoid excessive nitrogen which increases susceptibility",
        "estimated_cost": "₹1200-1800 per hectare per application",
        "effectiveness_duration": "10-14 days systemic protection",
        "reapplication_needed": "Repeat applications necessary under high disease pressure"
    },

    "brown_spot": {
        "name": "Brown Spot (Leaf Spot)",
        "treatment": "Mancozeb 75% WP @ 2 g per liter of water or Carbendazim 50% WP @ 1 g per liter",
        "prevention": "Balanced fertilization, avoid potassium deficiency, use disease-free seeds",
        "application_method": "Foliar spray with good coverage, target both upper and lower leaf surfaces",
        "secondary_treatment": "Azoxystrobin or Pyraclostrobin for broader spectrum control",
        "recommended_products": ["Mancozeb 75% WP (Dithane M-45)", "Carbendazim 50% WP", "Azoxystrobin 23% SC"],
        "timing": "Apply at disease onset or during favorable conditions (warm, humid weather)",
        "frequency": "2-3 sprays at 7-10 day intervals depending on disease severity",
        "safety_notes": "Use appropriate spray volume, avoid application during peak sunlight",
        "weather_considerations": "Apply in early morning or late evening, avoid high temperature periods",
        "crop_stage_compatibility": "Effective during all growth stages, particularly important during grain filling",
        "soil_compatibility": "Potassium-deficient soils increase susceptibility - address soil fertility",
        "estimated_cost": "₹800-1200 per hectare per application",
        "effectiveness_duration": "7-10 days protective action",
        "reapplication_needed": "Monitor and reapply if disease continues to spread"
    },

    "dead_heart": {
        "name": "Dead Heart (Yellow Stem Borer Damage)",
        "treatment": "Cartap hydrochloride 4G @ 10 kg per hectare or Chlorantraniliprole spray",
        "prevention": "Early planting, proper water management, use of pheromone traps for monitoring",
        "application_method": "Granular application to paddy water or foliar spray targeting larval stages",
        "secondary_treatment": "Flubendiamide or Cyantraniliprole for resistance management",
        "recommended_products": ["Cartap hydrochloride 4G", "Chlorantraniliprole 18.5% SC", "Flubendiamide 20% WG"],
        "timing": "Apply during early larval stages, monitor through pheromone trap catches",
        "frequency": "1-2 applications based on economic threshold levels (5-10% dead hearts)",
        "safety_notes": "Use granular applicator for uniform distribution, maintain water level in field",
        "weather_considerations": "Avoid spray application during rain, maintain field water level",
        "crop_stage_compatibility": "Critical during vegetative and reproductive stages when larvae are active",
        "soil_compatibility": "Maintain 5-7 cm water depth for optimal granular insecticide performance",
        "estimated_cost": "₹1500-2000 per hectare per application",
        "effectiveness_duration": "15-21 days residual activity",
        "reapplication_needed": "Reapply if monitoring indicates threshold crossing"
    },

    "downy_mildew": {
        "name": "Downy Mildew",
        "treatment": "Metalaxyl + Mancozeb @ 2 g per liter of water",
        "prevention": "Good air circulation, avoid overhead irrigation, remove infected plant debris",
        "application_method": "Foliar spray ensuring thorough coverage of all plant surfaces",
        "secondary_treatment": "Cymoxanil or Propamocarb for systemic control",
        "recommended_products": ["Metalaxyl-M 8% + Mancozeb 64% WP", "Cymoxanil 8% + Mancozeb 64% WP"],
        "timing": "Apply at first symptom appearance or during favorable conditions (cool, humid)",
        "frequency": "2-3 applications at 7-10 day intervals during susceptible periods",
        "safety_notes": "Rotate fungicides with different modes of action to prevent resistance",
        "weather_considerations": "Most effective when applied preventively before disease establishment",
        "crop_stage_compatibility": "Particularly important during rapid growth and reproductive stages",
        "soil_compatibility": "Well-drained soils and good air circulation reduce disease pressure",
        "estimated_cost": "₹1000-1400 per hectare per application",
        "effectiveness_duration": "7-10 days protective and curative action",
        "reapplication_needed": "Continue applications while conditions favor disease development"
    },

    "hispa": {
        "name": "Rice Hispa",
        "treatment": "Chlorpyrifos 20 EC @ 2.5 ml per liter or Neem oil 5%",
        "prevention": "Early planting, field sanitation, encourage natural predators (spiders, birds)",
        "application_method": "Foliar spray targeting adult beetles and larval mines on leaves",
        "secondary_treatment": "Imidacloprid or Thiamethoxam for systemic control",
        "recommended_products": ["Chlorpyrifos 20% EC", "Neem oil 0.03% EC", "Imidacloprid 17.8% SL"],
        "timing": "Apply when pest population reaches economic threshold (2-3 adults/hill)",
        "frequency": "1-2 applications based on pest population monitoring",
        "safety_notes": "Time application to target adult beetles, avoid beneficial insect impact",
        "weather_considerations": "Apply during calm weather when beetles are active, avoid rain periods",
        "crop_stage_compatibility": "Most damaging during vegetative stage when leaves are actively growing",
        "soil_compatibility": "Maintain proper water management to encourage natural predator activity",
        "estimated_cost": "₹600-1000 per hectare per application",
        "effectiveness_duration": "7-10 days contact and stomach poison action",
        "reapplication_needed": "Monitor pest population and reapply if threshold exceeded"
    },
    
    "normal": {
        "name": "Healthy Paddy Leaf",
        "treatment": "No treatment required - maintain good agricultural practices",
        "prevention": "Continue balanced fertilization, proper water management, regular monitoring",
        "application_method": "Maintain current crop management practices",
        "secondary_treatment": "Preventive foliar nutrition if needed for plant health",
        "recommended_products": ["Balanced NPK fertilizer", "Micronutrient mix", "Bio-stimulants"],
        "timing": "Continue regular crop management schedule",
        "frequency": "Standard crop management practices as per growth stage",
        "safety_notes": "Maintain field hygiene and monitoring for early problem detection",
        "weather_considerations": "Adapt management practices based on weather conditions",
        "crop_stage_compatibility": "Maintain plant health throughout all growth stages",
        "soil_compatibility": "Maintain optimal soil conditions for healthy plant growth",
        "estimated_cost": "Regular crop maintenance costs only",
        "effectiveness_duration": "Continuous plant health maintenance",
        "reapplication_needed": "Continue standard crop management practices"
    },

    "tungro": {
        "name": "Rice Tungro Disease",
        "treatment": "Control vector (Green Leafhopper) using Imidacloprid and rogue infected plants",
        "prevention": "Use resistant varieties, synchronous planting, control vector populations",
        "application_method": "Vector control through insecticide application and removal of infected plants",
        "secondary_treatment": "Seedling treatment with systemic insecticides for early protection",
        "recommended_products": ["Imidacloprid 17.8% SL", "Thiamethoxam 25% WG", "Carbofuran 3G"],
        "timing": "Early vector control is critical - apply during seedling and early vegetative stages",
        "frequency": "Multiple applications based on vector monitoring, rogue infected plants continuously",
        "safety_notes": "Focus on vector control rather than direct disease treatment, use integrated approach",
        "weather_considerations": "Monitor vector populations which increase during favorable weather",
        "crop_stage_compatibility": "Most critical during early growth stages when plants are most susceptible",
        "soil_compatibility": "Good drainage and proper field preparation reduce vector breeding sites",
        "estimated_cost": "₹1200-1800 per hectare for vector control program",
        "effectiveness_duration": "Vector control provides 10-15 days protection",
        "reapplication_needed": "Continuous monitoring and control based on vector population dynamics"
    }

}